"""initial migration

Revision ID: 2d06748c5fe8
Revises:
Create Date: 2025-04-26 22:39:20.677937

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2d06748c5fe8"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("email", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.drop_table("emp_salary")
    op.drop_table("emp")
    op.drop_table("events")
    op.drop_table("department")
    op.drop_table("employees")
    op.drop_table("customers")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "customers",
        sa.Column("order_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("customer_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("order_date", sa.DATE(), autoincrement=False, nullable=True),
        sa.Column("price", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("order_id", name="customers_pkey"),
    )
    op.create_table(
        "employees",
        sa.Column("emp_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "emp_name", sa.VARCHAR(length=50), autoincrement=False, nullable=True
        ),
        sa.Column(
            "dept_name", sa.VARCHAR(length=50), autoincrement=False, nullable=True
        ),
        sa.Column("salary", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("emp_id", name="employees_pkey"),
    )
    op.create_table(
        "department",
        sa.Column("dept_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "dept_name", sa.VARCHAR(length=50), autoincrement=False, nullable=True
        ),
        sa.Column(
            "location", sa.VARCHAR(length=50), autoincrement=False, nullable=True
        ),
        sa.PrimaryKeyConstraint("dept_id", name="department_pkey"),
    )
    op.create_table(
        "events",
        sa.Column("id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("event", sa.VARCHAR(length=255), autoincrement=False, nullable=True),
        sa.Column("year", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("gold", sa.VARCHAR(length=255), autoincrement=False, nullable=True),
        sa.Column("silver", sa.VARCHAR(length=255), autoincrement=False, nullable=True),
        sa.Column("bronze", sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    )
    op.create_table(
        "emp",
        sa.Column("emp_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "emp_name", sa.VARCHAR(length=50), autoincrement=False, nullable=True
        ),
        sa.Column("manager_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("emp_id", name="emp_pkey"),
    )
    op.create_table(
        "emp_salary",
        sa.Column("emp_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("name", sa.VARCHAR(length=20), autoincrement=False, nullable=False),
        sa.Column("salary", sa.VARCHAR(length=30), autoincrement=False, nullable=True),
        sa.Column("dept_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.drop_table("users")
    # ### end Alembic commands ###
